# Generated by Django 3.2.16 on 2023-01-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20230102_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
