# Generated by Django 3.2.16 on 2023-01-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='num_seats',
            field=models.CharField(choices=[(2, 'Table for 2'), (4, 'Table for 4'), (5, 'Table for 5'), (6, 'Table for 6')], default=2, max_length=10),
        ),
    ]
