# Generated by Django 3.2.16 on 2023-01-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_table_num_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='num_seats',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('6', '6')], default='2', max_length=10),
        ),
    ]
