# Generated by Django 3.2.16 on 2023-01-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_table_num_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField()),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('special_requirments', models.CharField(max_length=50)),
                ('Approved', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.table')),
            ],
        ),
    ]
