# Generated by Django 3.2.16 on 2023-01-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_booking_booking_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Approved',
            new_name='approved',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(choices=[('8:00', '8:00'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], default='8:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.IntegerField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('6', '6')], default=2),
        ),
    ]
