# Generated by Django 3.2.16 on 2023-01-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20230103_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='booked',
            new_name='has_booking',
        ),
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
        migrations.RemoveField(
            model_name='table',
            name='time',
        ),
    ]
