# Generated by Django 3.2.16 on 2023-01-03 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0015_auto_20230103_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_num',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='special_requirments',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(),
        ),
    ]
