# Generated by Django 3.2.16 on 2023-01-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_booking_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='has_booking',
        ),
        migrations.AddField(
            model_name='table',
            name='num_of_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
