# Generated by Django 3.2.16 on 2023-01-11 10:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20230110_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='menu item', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='menu item', max_length=20)),
                ('price', models.IntegerField(default=9.99)),
                ('img', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
