# Generated by Django 3.2.16 on 2023-01-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='course',
            field=models.CharField(choices=[('main', 'main'), ('starter', 'starter'), ('side', 'side'), ('desert', 'desert')], default='main', max_length=20),
        ),
    ]
