# Generated by Django 3.2.16 on 2023-01-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20230112_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (5, '5'), (6, '6')], default=2),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default='menu item', max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_seats',
            field=models.CharField(choices=[(2, '2'), (4, '4'), (5, '5'), (6, '6')], default='2', max_length=10),
        ),
    ]
