# Generated by Django 3.2.16 on 2023-01-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_alter_table_num_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
