# Generated by Django 3.2.16 on 2023-01-25 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_alter_booking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(choices=[(datetime.time(10, 0), '10 AM'), (datetime.time(11, 0), '11 AM'), (datetime.time(12, 0), '12 AM'), (datetime.time(13, 0), '1 PM'), (datetime.time(14, 0), '2 PM'), (datetime.time(15, 0), '3 PM'), (datetime.time(16, 0), '4 PM')], default='10 AM'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
