# Generated by Django 3.2.16 on 2023-01-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20230125_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
    ]
